services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/usr/app
            - /usr/app/node_modules
